version: "3"
services:
  redis:
    image: redis
    expose:
    - 6379
    volumes:
    - redis:/data

  postgres:
    image: postgres
    expose:
    - 5432
    volumes:
    - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: zspec
      POSTGRES_USER: zspec
      POSTGRES_DB: zspec

  client:
    image: ruby:2.6
    command: ./hack/client/entrypoint.sh
    volumes:
    - ./:/app
    - bundle:/usr/local/bundle
    depends_on:
    - redis
    - postgres
    working_dir: /app
    environment:
      ZSPEC_REDIS_HOST: redis
      ZSPEC_REDIS_PORT: 6379
      ZSPEC_BUILD_NUMBER: '1'
      ZSPEC_POSTGRES_HOST: postgres
      ZSPEC_POSTGRES_USER: zspec
      ZSPEC_POSTGRES_DB: zspec
      ZSPEC_POSTGRES_PASSWORD: zspec
      NODE_NAME: zspec-node
      POD_NAME: zspec-pod

  worker:
    image: ruby:2.6
    command: ./hack/worker/entrypoint.sh
    volumes:
    - ./:/app
    - bundle:/usr/local/bundle
    depends_on:
    - redis
    - client
    - postgres
    working_dir: /app
    environment:
      ZSPEC_REDIS_HOST: redis
      ZSPEC_REDIS_PORT: 6379
      ZSPEC_BUILD_NUMBER: '1'
      ZSPEC_POSTGRES_HOST: postgres
      ZSPEC_POSTGRES_USER: zspec
      ZSPEC_POSTGRES_DB: zspec
      ZSPEC_POSTGRES_PASSWORD: zspec
      NODE_NAME: zspec-node
      POD_NAME: zspec-pod

volumes:
  bundle:
  redis:
  postgres:
